In [1]:
##Numpy

In [2]:
##Numpy is a fundamental library for scintific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.

In [6]:
import numpy as np

In [9]:
arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
arr1=np.array([1,1,2,3,4,5,6])
arr2=np.array([4,4,5,6,1,2,3])

print("Addition:", arr1+arr2)

print("Substraction", arr2-arr1)

print("Multiply", arr1*arr2)




Addition: [5 5 7 9 5 7 9]
Substraction [ 3  3  3  3 -3 -3 -3]
Multiply [ 4  4 10 18  4 10 18]


In [19]:
arr=np.array([1,2,2,3,4,5])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.         1.41421356 1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561    7.3890561   20.08553692  54.59815003
 148.4131591 ]
[ 0.84147098  0.90929743  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 0.69314718 1.09861229 1.38629436 1.60943791]


In [21]:
arr1=np.array(([1,2,3,4],[4,5,6,7],[4,5,2,9]))

print("array:\n",arr1)

array:
 [[1 2 3 4]
 [4 5 6 7]
 [4 5 2 9]]


In [29]:
print(arr[0])

1


In [30]:
print(arr[3])

3


In [32]:
print(arr[6:1])

[]


In [36]:
arr=np.array([23,45,21,32,64,82])

mean=np.mean(arr)
print("Mean:",mean)

median=np.median(arr)
print("Median:",median)

std_dev=np.std(arr)
print("STd_dev:",std_dev)


var=np.var(arr)
print("Var:",var)

Mean: 44.5
Median: 38.5
STd_dev: 22.20172665957913
Var: 492.9166666666667


In [37]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
data[(data>5)&(data<10)]

array([6, 7, 8, 9])